# **This colab file shows how to detect object using YOLOv5 and SKU110K-6799_good_images dataset (which is made after ignoring the corrupted images from subset of SKU110K dataset (SKU110k_6799))**

Code Reference links: 

1. https://github.com/ultralytics/yolov5

2. https://colab.research.google.com/github/ultralytics/yolov5/blob/master/tutorial.ipynb#scrollTo=7mGmQbAO5pQb

3. https://www.youtube.com/watch?v=2nR2e4J4ZaI&t=1025s

4. https://github.com/ultralytics/yolov5/wiki/Train-Custom-Data

# To Setup

Clone repo, install dependencies and check PyTorch and GPU.

In [ ]:
#https://github.com/ultralytics/yolov5/wiki/Train-Custom-Data
#https://github.com/ultralytics/yolov5
!git clone https://github.com/ultralytics/yolov5  # clone repo
%cd yolov5
%pip install -qr requirements.txt  # install dependencies

import torch
from IPython.display import Image, clear_output  # to display images

clear_output()
print(f"Setup complete. Using torch {torch.__version__} ({torch.cuda.get_device_properties(0).name if torch.cuda.is_available() else 'CPU'})")

Setup complete. Using torch 1.9.0+cu102 (Tesla T4)


# To Use the Dataset 

* ### There are three ways to use the dataset:

1. Download dataset in your local PC and upload dataset directly on colab notebook by clicking on `Files icon in left panel-->right click and upload--->choose dataset path-->click open`. So it will be uploaded in colab notebook. But keep in mind when notebook is connected, you need to upload every time again.

2. Download dataset using `!wget` command and unzip it using `!unzip` command. In this option, you need to run the command every time once notebook is disconnected, so it will take long time to download and unzip the dataset, it depends on datset size.

3. The best way to use the large datset is to save the dataset in your Google drive and use directly after mounting google drive.

In [ ]:
# Method 1 is directly upload in colab as explained in above point 1
# Method 2
# To download and unzip the SKU110K-6799_good_images dataset

#!wget {URL link to download dataset} # To download the dataset
#!tar -xvf {path to untar the dataset} #To untar the dataset
#!unzip {path to unzip the dataset} # to unzip the datset

In [ ]:
# Method 3
# To mount Google drive to use SKU110K-6799_good_images dataset

from google.colab import drive
drive.mount('/content/gdrive/')

Mounted at /content/gdrive/


# For 50 Epochs and 16 Batch Size

## 1. Train 

### Train command represents following parameters:

>*   **`--img`**: Define input image size. The original image size is 1024 × 1024, compress to smaller size make the training process faster.
>*   **`--batch`**: Determine the batch size. For example, if the batch size is 16 and the training set contains 8219 images, so the number of batches will be 8219 ÷ 16 = 513. 
>*   **`--epochs`**: Define the number of training epochs. An epoch is responsible for learning all input images, in other words, training all input.  The number of epochs represents the number of times the model trains all the inputs and updates the weights to get closer to the ground truth labels.
>*   **`--data`**: The path to data.yaml file containing the summary of the dataset. The model evaluation process is executed immediately after each epoch, so the model will also access the validation directory via the path in data.yaml file and use its contents for 
evaluation at that moment.
>*   **`--weights`**: Specify a path to weights. A pretrained weight can be used for saving training time. If it is left blank or not given, the model will automatically initialize random weights for training.
>*   **`--project`**: Name of result folder. The model will store all the results performed during training in a directory. If it is not given, than all training results are saved to runs/train/ with incrementing run directories, i.e. runs/train/exp2, runs/train/exp3 etc.
>*   **`--cache`**: Cache images for training faster.

### This part shows training using YOLOv5 with Custom Dataset (SKU110K-6799_good_images) with 50 epochs, 640 image size and 16 batch size.

1. In the {x}.yaml file, give all the path of train, test and validation folders from the dataset.
2. Give {x}.yaml file path as `--data` argumant in following command.
3. Give your results folder's path as `--project` argument, where you want to save your results.

In [ ]:
# To train using YOLOv5 and dataset SKU110K-6799_good_images with 50 epochs, 640 image size and 16 batch size

!python train.py --img 640 --batch 16 --epochs 50 --data /content/gdrive/MyDrive/Object_Detection_in_Dense_Conditions/SKU110K-6799-good_images.yaml --project /content/gdrive/MyDrive/Object_Detection_in_Dense_Conditions/SKU110K-6799_good_images_results/16_640_50/640 --cache

train: weights=yolov5s.pt, cfg=, data=/content/gdrive/MyDrive/Object_Detection_in_Dense_Conditions/SKU110K-6799-Full_images.yaml, hyp=data/hyps/hyp.scratch.yaml, epochs=50, batch_size=16, imgsz=640, rect=False, resume=False, nosave=False, noval=False, noautoanchor=False, evolve=None, bucket=, cache_images=True, image_weights=False, device=, multi_scale=False, single_cls=False, adam=False, sync_bn=False, workers=8, project=/content/gdrive/MyDrive/Object_Detection_in_Dense_Conditions/SKU110K-6799_Full_images_results/640, entity=None, name=exp, exist_ok=False, quad=False, linear_lr=False, label_smoothing=0.0, upload_dataset=False, bbox_interval=-1, save_period=-1, artifact_alias=latest, local_rank=-1
github: up to date with https://github.com/ultralytics/yolov5 ✅
YOLOv5 🚀 v5.0-304-g2c073cd torch 1.9.0+cu102 CUDA:0 (Tesla P100-PCIE-16GB, 16280.875MB)

hyperparameters: lr0=0.01, lrf=0.2, momentum=0.937, weight_decay=0.0005, warmup_epochs=3.0, warmup_momentum=0.8, warmup_bias_lr=0.1, box=0.0

## 2. Validate

* Use above trained model `best.pt` as `--weights` argument and validate a model's accuracy with 416 image size on SKU110K-6799_good_images dataset using following command line.

* All validation results are saved to runs/val/ with incrementing run directories, i.e. runs/val/exp2, runs/val/exp3 etc., if `--project` argument is not given.

In [ ]:
# To validate model's accuracy using 416 image size on SKU110K-6799_good_images

!python val.py --task test --batch-size 16 --img 416 --weights /content/gdrive/MyDrive/Object_Detection_in_Dense_Conditions/SKU110K-6799_16_640_50_good_images_best.pt --data /content/gdrive/MyDrive/Object_Detection_in_Dense_Conditions/SKU110K-6799-good_images.yaml --project /content/gdrive/MyDrive/Object_Detection_in_Dense_Conditions/SKU110K-6799_good_images_results/16_640_50/416

100% 755k/755k [00:00<00:00, 26.4MB/s]
val: data=/content/gdrive/MyDrive/Object_Detection_in_Dense_Conditions/SKU110K-6799-good_images.yaml, weights=['/content/gdrive/MyDrive/Object_Detection_in_Dense_Conditions/SKU110K-6799_16_640_50_good_images_best.pt'], batch_size=16, imgsz=416, conf_thres=0.001, iou_thres=0.6, task=test, device=, single_cls=False, augment=False, verbose=False, save_txt=False, save_hybrid=False, save_conf=False, save_json=False, project=/content/gdrive/MyDrive/Object_Detection_in_Dense_Conditions/SKU110K-6799_good_images_results/16_640_50/416, name=exp, exist_ok=False, half=False
YOLOv5 🚀 v5.0-407-g5487451 torch 1.9.0+cu102 CUDA:0 (Tesla T4, 15109.75MB)

Fusing layers... 
Model Summary: 224 layers, 7053910 parameters, 0 gradients, 16.3 GFLOPs
test: Scanning '/content/gdrive/MyDrive/Object_Detection_in_Dense_Conditions/SKU110K-6799-good_images/SKU110K-6799-good_images/evaluation_pano/labels.cache' images and labels... 1620 found, 0 missing, 0 empty, 131 corrupted: 1

* Use above trained model `best.pt` as `--weights` argument and validate a model's accuracy with 640 image size on SKU110K-6799_good_images dataset using following command line.

In [ ]:
# To validate model's accuracy using 640 image size on SKU110K-6799_good_images

!python val.py --task test --batch-size 16 --img 640 --weights /content/gdrive/MyDrive/Object_Detection_in_Dense_Conditions/SKU110K-6799_16_640_50_good_images_best.pt --data /content/gdrive/MyDrive/Object_Detection_in_Dense_Conditions/SKU110K-6799-good_images.yaml --project /content/gdrive/MyDrive/Object_Detection_in_Dense_Conditions/SKU110K-6799_good_images_results/16_640_50

val: data=/content/gdrive/MyDrive/Object_Detection_in_Dense_Conditions/SKU110K-6799-good_images.yaml, weights=['/content/gdrive/MyDrive/Object_Detection_in_Dense_Conditions/SKU110K-6799_16_640_50_good_images_best.pt'], batch_size=16, imgsz=640, conf_thres=0.001, iou_thres=0.6, task=test, device=, single_cls=False, augment=False, verbose=False, save_txt=False, save_hybrid=False, save_conf=False, save_json=False, project=/content/gdrive/MyDrive/Object_Detection_in_Dense_Conditions/SKU110K-6799_good_images_results/16_640_50, name=exp, exist_ok=False, half=False
YOLOv5 🚀 v5.0-310-g63dd65e torch 1.9.0+cu102 CUDA:0 (Tesla V100-SXM2-16GB, 16160.5MB)

Fusing layers... 
/usr/local/lib/python3.7/dist-packages/torch/nn/functional.py:718: UserWarning: Named tensors and all their associated APIs are an experimental feature and subject to change. Please do not use them for anything important until they are released as stable. (Triggered internally at  /pytorch/c10/core/TensorImpl.h:1156.)
  return t

* Use above trained model `best.pt` as `--weights` argument and validate a model's accuracy with 1024 image size on SKU110K-6799_good_images dataset using following command line.

In [ ]:
# To validate model's accuracy using 1024 image size on SKU110K-6799_good_images

!python val.py --task test --batch-size 16 --img 1024 --weights /content/gdrive/MyDrive/Object_Detection_in_Dense_Conditions/SKU110K-6799_16_640_50_good_images_best.pt --data /content/gdrive/MyDrive/Object_Detection_in_Dense_Conditions/SKU110K-6799-good_images.yaml --project /content/gdrive/MyDrive/Object_Detection_in_Dense_Conditions/SKU110K-6799_good_images_results/16_640_50/1024

val: data=/content/gdrive/MyDrive/Object_Detection_in_Dense_Conditions/SKU110K-6799-good_images.yaml, weights=['/content/gdrive/MyDrive/Object_Detection_in_Dense_Conditions/SKU110K-6799_16_640_50_good_images_best.pt'], batch_size=16, imgsz=1024, conf_thres=0.001, iou_thres=0.6, task=test, device=, single_cls=False, augment=False, verbose=False, save_txt=False, save_hybrid=False, save_conf=False, save_json=False, project=/content/gdrive/MyDrive/Object_Detection_in_Dense_Conditions/SKU110K-6799_good_images_results/16_640_50/1024, name=exp, exist_ok=False, half=False
YOLOv5 🚀 v5.0-407-g5487451 torch 1.9.0+cu102 CUDA:0 (Tesla T4, 15109.75MB)

Fusing layers... 
Model Summary: 224 layers, 7053910 parameters, 0 gradients, 16.3 GFLOPs
test: Scanning '/content/gdrive/MyDrive/Object_Detection_in_Dense_Conditions/SKU110K-6799-good_images/SKU110K-6799-good_images/evaluation_pano/labels.cache' images and labels... 1620 found, 0 missing, 0 empty, 131 corrupted: 100% 1751/1751 [00:00<?, ?it/s]test: W

* Use above trained model `best.pt` as `--weights` argument and validate a model's accuracy with 2048 image size on SKU110K-6799_good_images dataset using following command line.

In [ ]:
# To validate model's accuracy using 2048 image size on SKU110K-6799_good_images

!python val.py --task test --batch-size 16 --img 2048 --weights /content/gdrive/MyDrive/Object_Detection_in_Dense_Conditions/SKU110K-6799_16_640_50_good_images_best.pt --data /content/gdrive/MyDrive/Object_Detection_in_Dense_Conditions/SKU110K-6799-good_images.yaml --project /content/gdrive/MyDrive/Object_Detection_in_Dense_Conditions/SKU110K-6799_good_images_results/16_640_50/2048

val: data=/content/gdrive/MyDrive/Object_Detection_in_Dense_Conditions/SKU110K-6799-good_images.yaml, weights=['/content/gdrive/MyDrive/Object_Detection_in_Dense_Conditions/SKU110K-6799_16_640_50_good_images_best.pt'], batch_size=16, imgsz=2048, conf_thres=0.001, iou_thres=0.6, task=test, device=, single_cls=False, augment=False, verbose=False, save_txt=False, save_hybrid=False, save_conf=False, save_json=False, project=/content/gdrive/MyDrive/Object_Detection_in_Dense_Conditions/SKU110K-6799_good_images_results/16_640_50/2048, name=exp, exist_ok=False, half=False
YOLOv5 🚀 v5.0-407-g5487451 torch 1.9.0+cu102 CUDA:0 (Tesla T4, 15109.75MB)

Fusing layers... 
Model Summary: 224 layers, 7053910 parameters, 0 gradients, 16.3 GFLOPs
test: Scanning '/content/gdrive/MyDrive/Object_Detection_in_Dense_Conditions/SKU110K-6799-good_images/SKU110K-6799-good_images/evaluation_pano/labels.cache' images and labels... 1620 found, 0 missing, 0 empty, 131 corrupted: 100% 1751/1751 [00:00<?, ?it/s]test: W

## 3. Detect

* Use following command to detect the objects from images. You can set your detection images path using `--source` argument. 

* All detecting results are saved to runs/detect/ with incrementing run directories, i.e. runs/detect/exp2, runs/detect/exp3 etc., if `--project` argument is not given.

In [ ]:
# To detect objects from given source path's images

!python detect.py --save-txt --save-conf --img 640  --weights /content/gdrive/MyDrive/Object_Detection_in_Dense_Conditions/SKU110K-6799_16_640_50_good_images_best.pt  --project /content/gdrive/MyDrive/Object_Detection_in_Dense_Conditions/SKU110K-6799_good_images_results/16_640_50/640 --source /content/gdrive/MyDrive/Object_Detection_in_Dense_Conditions/SKU-110K/images/test_0.jpg

detect: weights=['/content/gdrive/MyDrive/Object_Detection_in_Dense_Conditions/SKU110K-6799_16_640_50_good_images_best.pt'], source=/content/gdrive/MyDrive/Object_Detection_in_Dense_Conditions/SKU-110K/images/test_0.jpg, imgsz=640, conf_thres=0.25, iou_thres=0.45, max_det=1000, device=, view_img=False, save_txt=True, save_conf=True, save_crop=False, nosave=False, classes=None, agnostic_nms=False, augment=False, visualize=False, update=False, project=/content/gdrive/MyDrive/Object_Detection_in_Dense_Conditions/SKU110K-6799_good_images_results/16_640_50, name=exp, exist_ok=False, line_thickness=3, hide_labels=False, hide_conf=False, half=False
YOLOv5 🚀 v5.0-310-g63dd65e torch 1.9.0+cu102 CUDA:0 (Tesla V100-SXM2-16GB, 16160.5MB)

Fusing layers... 
/usr/local/lib/python3.7/dist-packages/torch/nn/functional.py:718: UserWarning: Named tensors and all their associated APIs are an experimental feature and subject to change. Please do not use them for anything important until they are released 

# For 50 Epochs and 64 Batch Size

## 1. Train 

### This part shows training using YOLOv5 with Custom Dataset (SKU110K-6799_good_images) with 50 epochs, 640 image size and 64 batch size.

1. In the {x}.yaml file, give all the path of train, test and validation folders from the dataset.
2. Give {x}.yaml file path as `--data` argumant in following command.
3. Give your results folder's path as `--project` argument, where you want to save your results.

In [ ]:
# To train using YOLOv5 and dataset SKU110K-6799_good_images with 50 epochs, 640 image size and 64 batch size

!python train.py --img 640 --batch 64 --epochs 50 --data /content/gdrive/MyDrive/Object_Detection_in_Dense_Conditions/SKU110K-6799-good_images.yaml --project /content/gdrive/MyDrive/Object_Detection_in_Dense_Conditions/SKU110K-6799_good_images_results/64_640_50/640 --cache

train: weights=yolov5s.pt, cfg=, data=/content/gdrive/MyDrive/Object_Detection_in_Dense_Conditions/SKU110K-6799-good_images.yaml, hyp=data/hyps/hyp.scratch.yaml, epochs=50, batch_size=64, imgsz=640, rect=False, resume=False, nosave=False, noval=False, noautoanchor=False, evolve=None, bucket=, cache_images=True, image_weights=False, device=, multi_scale=False, single_cls=False, adam=False, sync_bn=False, workers=8, project=/content/gdrive/MyDrive/Object_Detection_in_Dense_Conditions/SKU110K-6799_good_images_results/64_640_50, entity=None, name=exp, exist_ok=False, quad=False, linear_lr=False, label_smoothing=0.0, upload_dataset=False, bbox_interval=-1, save_period=-1, artifact_alias=latest, local_rank=-1
remote: Enumerating objects: 11, done.
remote: Counting objects: 100% (11/11), done.
remote: Compressing objects: 100% (7/7), done.
remote: Total 11 (delta 5), reused 5 (delta 4), pack-reused 0
Unpacking objects: 100% (11/11), done.
From https://github.com/ultralytics/yolov5
   63dd65e.

## 2. Validate

* Use above trained model `best.pt` as `--weights` argument and validate a model's accuracy with 416 image size on SKU110K-6799_good_images dataset using following command line.

* All validation results are saved to runs/val/ with incrementing run directories, i.e. runs/val/exp2, runs/val/exp3 etc., if `--project` argument is not given.

In [ ]:
# To validate model's accuracy using 416 image size on SKU110K-6799_good_images

!python val.py --task test --batch-size 64 --img 416 --weights /content/gdrive/MyDrive/Object_Detection_in_Dense_Conditions/SKU110K-6799_64_640_50_good_images_best.pt --data /content/gdrive/MyDrive/Object_Detection_in_Dense_Conditions/SKU110K-6799-good_images.yaml --project /content/gdrive/MyDrive/Object_Detection_in_Dense_Conditions/SKU110K-6799_good_images_results/64_640_50/416

val: data=/content/gdrive/MyDrive/Object_Detection_in_Dense_Conditions/SKU110K-6799-good_images.yaml, weights=['/content/gdrive/MyDrive/Object_Detection_in_Dense_Conditions/SKU110K-6799_64_640_50_good_images_best.pt'], batch_size=64, imgsz=416, conf_thres=0.001, iou_thres=0.6, task=test, device=, single_cls=False, augment=False, verbose=False, save_txt=False, save_hybrid=False, save_conf=False, save_json=False, project=/content/gdrive/MyDrive/Object_Detection_in_Dense_Conditions/SKU110K-6799_good_images_results/64_640_50/416, name=exp, exist_ok=False, half=False
YOLOv5 🚀 v5.0-407-g5487451 torch 1.9.0+cu102 CUDA:0 (Tesla T4, 15109.75MB)

Fusing layers... 
Model Summary: 224 layers, 7053910 parameters, 0 gradients, 16.3 GFLOPs
test: Scanning '/content/gdrive/MyDrive/Object_Detection_in_Dense_Conditions/SKU110K-6799-good_images/SKU110K-6799-good_images/evaluation_pano/labels.cache' images and labels... 1620 found, 0 missing, 0 empty, 131 corrupted: 100% 1751/1751 [00:00<?, ?it/s]test: WAR

* Use above trained model `best.pt` as `--weights` argument and validate a model's accuracy with 640 image size on SKU110K-6799_good_images dataset using following command line.

In [ ]:
# To validate model's accuracy using 640 image size on SKU110K-6799_good_images

!python val.py --task test --batch-size 64 --img 640 --weights /content/gdrive/MyDrive/Object_Detection_in_Dense_Conditions/SKU110K-6799_64_640_50_good_images_best.pt --data /content/gdrive/MyDrive/Object_Detection_in_Dense_Conditions/SKU110K-6799-good_images.yaml --project /content/gdrive/MyDrive/Object_Detection_in_Dense_Conditions/SKU110K-6799_good_images_results/64_640_50/640

val: data=/content/gdrive/MyDrive/Object_Detection_in_Dense_Conditions/SKU110K-6799-good_images.yaml, weights=['/content/gdrive/MyDrive/Object_Detection_in_Dense_Conditions/SKU110K-6799_64_640_50_good_images_best.pt'], batch_size=64, imgsz=640, conf_thres=0.001, iou_thres=0.6, task=test, device=, single_cls=False, augment=False, verbose=False, save_txt=False, save_hybrid=False, save_conf=False, save_json=False, project=/content/gdrive/MyDrive/Object_Detection_in_Dense_Conditions/SKU110K-6799_good_images_results/64_640_50, name=exp, exist_ok=False, half=False
YOLOv5 🚀 v5.0-312-gd17b45e torch 1.9.0+cu102 CUDA:0 (Tesla P100-PCIE-16GB, 16280.875MB)

Fusing layers... 
/usr/local/lib/python3.7/dist-packages/torch/nn/functional.py:718: UserWarning: Named tensors and all their associated APIs are an experimental feature and subject to change. Please do not use them for anything important until they are released as stable. (Triggered internally at  /pytorch/c10/core/TensorImpl.h:1156.)
  return

* Use above trained model `best.pt` as `--weights` argument and validate a model's accuracy with 1024 image size on SKU110K-6799_good_images dataset using following command line.

In [ ]:
# To validate model's accuracy using 1024 image size on SKU110K-6799_good_images

!python val.py --task test --batch-size 64 --img 1024 --weights /content/gdrive/MyDrive/Object_Detection_in_Dense_Conditions/SKU110K-6799_64_640_50_good_images_best.pt --data /content/gdrive/MyDrive/Object_Detection_in_Dense_Conditions/SKU110K-6799-good_images.yaml --project /content/gdrive/MyDrive/Object_Detection_in_Dense_Conditions/SKU110K-6799_good_images_results/64_640_50/1024

val: data=/content/gdrive/MyDrive/Object_Detection_in_Dense_Conditions/SKU110K-6799-good_images.yaml, weights=['/content/gdrive/MyDrive/Object_Detection_in_Dense_Conditions/SKU110K-6799_64_640_50_good_images_best.pt'], batch_size=64, imgsz=1024, conf_thres=0.001, iou_thres=0.6, task=test, device=, single_cls=False, augment=False, verbose=False, save_txt=False, save_hybrid=False, save_conf=False, save_json=False, project=/content/gdrive/MyDrive/Object_Detection_in_Dense_Conditions/SKU110K-6799_good_images_results/64_640_50/1024, name=exp, exist_ok=False, half=False
YOLOv5 🚀 v5.0-407-g5487451 torch 1.9.0+cu102 CUDA:0 (Tesla T4, 15109.75MB)

Fusing layers... 
Model Summary: 224 layers, 7053910 parameters, 0 gradients, 16.3 GFLOPs
test: Scanning '/content/gdrive/MyDrive/Object_Detection_in_Dense_Conditions/SKU110K-6799-good_images/SKU110K-6799-good_images/evaluation_pano/labels.cache' images and labels... 1620 found, 0 missing, 0 empty, 131 corrupted: 100% 1751/1751 [00:00<?, ?it/s]test: W

* Use above trained model `best.pt` as `--weights` argument and validate a model's accuracy with 2048 image size on SKU110K-6799_good_images dataset using following command line.

In [ ]:
# To validate model's accuracy using 2048 image size on SKU110K-6799_good_images

!python val.py --task test --batch-size 64 --img 2048 --weights /content/gdrive/MyDrive/Object_Detection_in_Dense_Conditions/SKU110K-6799_64_640_50_good_images_best.pt --data /content/gdrive/MyDrive/Object_Detection_in_Dense_Conditions/SKU110K-6799-good_images.yaml --project /content/gdrive/MyDrive/Object_Detection_in_Dense_Conditions/SKU110K-6799_good_images_results/64_640_50/2048

val: data=/content/gdrive/MyDrive/Object_Detection_in_Dense_Conditions/SKU110K-6799-good_images.yaml, weights=['/content/gdrive/MyDrive/Object_Detection_in_Dense_Conditions/SKU110K-6799_64_640_50_good_images_best.pt'], batch_size=64, imgsz=2048, conf_thres=0.001, iou_thres=0.6, task=test, device=, single_cls=False, augment=False, verbose=False, save_txt=False, save_hybrid=False, save_conf=False, save_json=False, project=/content/gdrive/MyDrive/Object_Detection_in_Dense_Conditions/SKU110K-6799_good_images_results/64_640_50/2048, name=exp, exist_ok=False, half=False
YOLOv5 🚀 v5.0-407-g5487451 torch 1.9.0+cu102 CUDA:0 (Tesla T4, 15109.75MB)

Fusing layers... 
Model Summary: 224 layers, 7053910 parameters, 0 gradients, 16.3 GFLOPs
test: Scanning '/content/gdrive/MyDrive/Object_Detection_in_Dense_Conditions/SKU110K-6799-good_images/SKU110K-6799-good_images/evaluation_pano/labels.cache' images and labels... 1620 found, 0 missing, 0 empty, 131 corrupted: 100% 1751/1751 [00:00<?, ?it/s]test: W

## 3. Detect

* Use following command to detect the objects from images. You can set your detection images path using `--source` argument. 

* All detecting results are saved to runs/detect/ with incrementing run directories, i.e. runs/detect/exp2, runs/detect/exp3 etc., if `--project` argument is not given.

In [ ]:
# To detect objects from given source path's images

!python detect.py --save-txt --save-conf --img 640  --weights /content/gdrive/MyDrive/Object_Detection_in_Dense_Conditions/SKU110K-6799_64_640_50_good_images_best.pt  --project /content/gdrive/MyDrive/Object_Detection_in_Dense_Conditions/SKU110K-6799_good_images_results/64_640_50 --source /content/gdrive/MyDrive/Object_Detection_in_Dense_Conditions/SKU-110K/images/test_0.jpg

detect: weights=['/content/gdrive/MyDrive/Object_Detection_in_Dense_Conditions/SKU110K-6799_64_640_50_good_images_best.pt'], source=/content/gdrive/MyDrive/Object_Detection_in_Dense_Conditions/SKU-110K/images/test_0.jpg, imgsz=640, conf_thres=0.25, iou_thres=0.45, max_det=1000, device=, view_img=False, save_txt=True, save_conf=True, save_crop=False, nosave=False, classes=None, agnostic_nms=False, augment=False, visualize=False, update=False, project=/content/gdrive/MyDrive/Object_Detection_in_Dense_Conditions/SKU110K-6799_good_images_results/64_640_50, name=exp, exist_ok=False, line_thickness=3, hide_labels=False, hide_conf=False, half=False
YOLOv5 🚀 v5.0-312-gd17b45e torch 1.9.0+cu102 CPU

Fusing layers... 
/usr/local/lib/python3.7/dist-packages/torch/nn/functional.py:718: UserWarning: Named tensors and all their associated APIs are an experimental feature and subject to change. Please do not use them for anything important until they are released as stable. (Triggered internally at  

# To Convert Folder into Zip Folder

In [ ]:
import os
from os import path
import shutil
from shutil import make_archive
from zipfile import ZipFile
!zip -r /content/Full_train_640_16.zip /content/yolov5/runs/train/exp

  adding: content/yolov5/runs/train/exp/ (stored 0%)
  adding: content/yolov5/runs/train/exp/results.txt (deflated 66%)
  adding: content/yolov5/runs/train/exp/val_batch2_pred.jpg (deflated 1%)
  adding: content/yolov5/runs/train/exp/results.png (deflated 9%)
  adding: content/yolov5/runs/train/exp/opt.yaml (deflated 42%)
  adding: content/yolov5/runs/train/exp/events.out.tfevents.1626849109.0e988e9145f5.335.0 (deflated 93%)
  adding: content/yolov5/runs/train/exp/labels.jpg (deflated 23%)
  adding: content/yolov5/runs/train/exp/confusion_matrix.png (deflated 36%)
  adding: content/yolov5/runs/train/exp/val_batch1_labels.jpg (deflated 2%)
  adding: content/yolov5/runs/train/exp/labels_correlogram.jpg (deflated 22%)
  adding: content/yolov5/runs/train/exp/val_batch2_labels.jpg (deflated 1%)
  adding: content/yolov5/runs/train/exp/F1_curve.png (deflated 19%)
  adding: content/yolov5/runs/train/exp/P_curve.png (deflated 22%)
  adding: content/yolov5/runs/train/exp/val_batch0_pred.jpg (def

# To Download Zipped Folder from Colab to Local PC

In [ ]:
from google.colab import files
files.download('/content/results.zip')